version: '2'

tasks:

  install:
    cmds:
      - nimble install

  build:
    cmds:
      - nim c -o:./ribboncd{{exeExt}} -d:silence_rosencrantz src/ribboncd.nim 
    sources:
      - ./src/*.nim
      - ./src/**/.nim
    generates:
      - ribboncd{{exeExt}}

  test:
    cmds:
      - nimble test

  run:
    cmds:
      - nim c -o:./ribboncd{{exeExt}} -d:silence_rosencrantz -r src/ribboncd.nim

  release:
    cmds:
      - nimble build
    silent: true

  clean:
    cmds:
      - rm ribboncd{{exeExt}}
      - rm *.dll
