version: '2'

tasks:

  install:
    cmds:
      - nimble install

  build:
    cmds:
      - nim c -o:./ribboncd{{exeExt}} src/ribboncd.nim 
    sources:
      - ./src/*.nim
      - ./src/**/.nim
    generates:
      - ribboncd{{exeExt}}

  test:
    cmds:
      - nimble test

  run:
    cmds:
      - nim c -o:./ribboncd{{exeExt}} -r src/ribboncd.nim

  release:
    cmds:
      - nim c -d:release --opt:size --passL:-s -o:./ribboncd{{exeExt}} src/ribboncd.nim

  # linux x64 only - requires tar/gzip, zip, + mingw-w64-gcc for cross compilation
  bundle:
    cmds:
      # build linux x64 binary natively
      - nim c -d:release --cpu:amd64 --opt:size --passL:-s -o:./ribboncd src/ribboncd.nim
      # cross compile for windows
      - nim c -d:mingw -d:release --cpu:amd64 --opt:size --passL:-s -o:./ribboncd.exe src/ribboncd.nim
      # tar + zip binaries with included example config
      -  tar -cvzf ribboncd.linux64.tar.gz ribboncd ribboncd.example.conf.yml 
      - zip ribboncd.win64.zip ribboncd.exe ribboncd.example.conf.yml

  clean:
    ignore_error: true
    cmds:
      - rm ribboncd{{exeExt}}
      - rm *.dll
      - rm *.exe
      - rm *.zip
      - rm *.tar.gz

